
apache:
  build: ./apache/
  ports:
   - "80:80"
  links:
   - titter
   - login
   - storage
   - webgold
   - core


login:
  image: michbil/login-wrio-app
  ports:
   - "5000:5000"
  volumes:
   - ./configs/login-wrio-app/:/srv/config
  command: bash -c "cd /srv/www && cp /srv/config/config.json . && node server.js"

titter:
  image: michbil/titter-wrio-app
  ports:
   - "5001:5001"
  volumes:
   - ./configs/titter-wrio-app/:/srv/config
  command: bash -c "cd /srv/www && cp /srv/config/config.json . && node server.js"

storage:
  image: michbil/storage-wrio-app
  ports:
   - "5002:5002"
  volumes:
    - ./configs/storage-wrio-app/:/srv/config
  command: bash -c "cd /srv/www && cp /srv/config/config.json . && node server.js"

webgold:
  image: michbil/webgold-wrio-app
  ports:
   - "5003:5003"
  volumes:
    - ./configs/webgold-wrio-app/:/srv/config
  command: bash -c "cd /srv/www && cp /srv/config/config.json . && node server.js"


#chess:
#  build: ./Chess-WRIO-Game/
#  ports:
#   - "5005:5005"
#  volumes:
#   - ./Chess-WRIO-Game/:/srv/www/
#  links:
#    - titter

core:
  image: michbil/core-wrio-app
  ports:
   - "5004:5004"
  volumes:
  - ./configs/core-wrio-app/:/srv/config
  command: bash -c "cd /srv/www && gulp && cp /srv/config/config.json . && node server.js"

