
apache:
  build: ./apache/
  ports:
   - "80:80"
  links:
   - titter
   - login
   - storage
   - webgold
   - dev
   - core


login:
  image: michbil/login-wrio-app
  ports:
   - "5000:5000"
  volumes:
   - ./Login-WRIO-App/:/srv/www/

titter:
  image: michbil/titter-wrio-app
  ports:
   - "5001:5001"
  volumes:
   - ./Titter-WRIO-App/:/srv/www/

storage:
  image: michbil/storage-wrio-app
  ports:
   - "5002:5002"
  volumes:
   - ./Storage-WRIO-App/:/srv/www/

webgold:
  image: michbil/webgold-wrio-app
  ports:
   - "5003:5003"
  volumes:
   - ./webGold-WRIO-App/:/srv/www/

#chess:
#  build: ./Chess-WRIO-Game/
#  ports:
#   - "5005:5005"
#  volumes:
#   - ./Chess-WRIO-Game/:/srv/www/
#  links:
#    - titter

core:
  image: michbil/core-wrio-app
  ports:
   - "5004:5004"
  volumes:
   - ./Core-WRIO-App/:/srv/www/

